language: objective-c

branches:
only:
- master

xcode_project: PersoChecker.xcodeproj
osx_image: xcode7.3

script:
- xcodebuild clean build test -project PersoChecker.xcodeproj -scheme PersoCheckerTests